import type { ExamCode, Question, QuestionFormat } from "./types";

type Blueprint = {
  module: string; reference: string; context: string; prompt: string; answer: string;
  distractors: [string, string, string]; format?: QuestionFormat; dialogue?: Question["dialogue"];
};

const I1 = "1. Produtos de investimentos", I2 = "2. Alternativos, digitais e exterior";
const I3 = "3. Previdência complementar", I4 = "4. Risco, carteiras e performance";
const R1 = "1. Prospecção e relacionamento", R2 = "2. Análise de informações do cliente";
const R3 = "3. Indicação de investimentos", R4 = "4. Análise e monitoramento";

const ib: Blueprint[] = [
  {module:I1,reference:"PD C-Pro I 1.1.8",context:"Um fundo multimercado cobra administração e performance sobre o que exceder o CDI. Após queda de 8%, a cota recuperou 6%, mas não superou o pico ajustado.",prompt:"Ao analisar a cobrança, o especialista deve concluir que:",answer:"a recuperação parcial não autoriza, por si, nova performance; devem ser respeitados benchmark, periodicidade e linha d’água.",distractors:["qualquer retorno mensal positivo autoriza performance sobre todo o ganho.","a performance substitui a administração quando o fundo fica abaixo do CDI.","a linha d’água só se aplica no primeiro período do fundo."]},
  {module:I1,reference:"PD C-Pro I 1.2.3",context:"Um FIDC de recebíveis pulverizados apresenta baixa inadimplência histórica, mas a auditoria encontra documentação incompleta em parte relevante da amostra.",prompt:"Na análise das cotas, o ponto crítico é:",answer:"a qualidade e verificação do lastro, pois falhas documentais podem elevar riscos jurídico, operacional e de crédito.",distractors:["a pulverização, que garante liquidez diária e elimina risco de crédito.","a existência de cota sênior, que torna irrelevante a qualidade dos recebíveis.","a inadimplência passada baixa, que dispensa critérios de elegibilidade."]},
  {module:I1,reference:"PD C-Pro I 1.2.1",context:"Um FII de lajes tem vacância crescente, revisões contratuais próximas e cota com desconto sobre o valor patrimonial. O investidor vê arbitragem certa.",prompt:"O parecer tecnicamente correto deve indicar que:",answer:"o desconto pode refletir renda, vacância, liquidez e reprecificação dos imóveis; não existe convergência garantida ao valor patrimonial.",distractors:["o administrador deve recomprar a cota pelo valor patrimonial.","aluguéis impedem queda adicional da cota.","negociação em bolsa elimina risco de liquidez e mercado."]},
  {module:I1,reference:"PD C-Pro I 1.7.2.5",context:"Dois prefixados do mesmo emissor têm o mesmo yield. A vence em dois anos; B, sem cupons, em oito. A curva sobe 100 pontos-base.",prompt:"Mantidas as demais condições, espera-se que:",answer:"B sofra maior queda percentual por ter maior duration; convexidade melhora a aproximação para movimentos relevantes.",distractors:["A caia mais porque seu prazo curto concentra todo o risco.","ambos caiam igual por terem o mesmo yield.","B suba porque títulos sem cupom ganham com a alta das taxas."]},
  {module:I1,reference:"PD C-Pro I 1.7.2.4",context:"Uma exportadora receberá dólares em seis meses e teme valorização do real. Compara venda de futuro com compra de put de dólar.",prompt:"Qual distinção deve orientar a proteção?",answer:"o futuro fixa economicamente a taxa e gera ajustes; a put cria piso preservando cenário favorável, ao custo do prêmio.",distractors:["ambos preservam toda alta favorável sem custo ou ajuste.","a opção cria obrigação e o futuro apenas um direito.","vender dólar futuro aumenta, em vez de reduzir, a exposição da exportadora."]},
  {module:I1,reference:"PD C-Pro I 1.12",context:"Um COE de valor nominal protegido, ligado a índice externo, vence em quatro anos. O emissor deteriora e o cliente acredita ter garantia do FGC.",prompt:"A orientação correta é:",answer:"a proteção é obrigação do emissor, não cobertura ordinária do FGC; crédito, liquidez e payoff permanecem relevantes.",distractors:["a proteção nominal elimina risco de crédito.","todo COE bancário possui cobertura do FGC.","proteção nominal garante retorno real acima da inflação."]},
  {module:I1,reference:"PD C-Pro I 1.6",context:"Uma ação negocia com P/L abaixo dos pares, mas tem margem em queda, dívida crescente e fluxo de caixa livre negativo.",prompt:"A leitura consistente é:",answer:"o múltiplo baixo pode refletir deterioração; crescimento, caixa, risco e estrutura de capital precisam integrar a análise.",distractors:["P/L baixo prova subavaliação independentemente dos fundamentos.","lucro contábil torna irrelevante o fluxo de caixa livre.","dívida crescente reduz automaticamente o custo do capital próprio."]},
  {module:I1,reference:"PD C-Pro I 1.4",context:"Uma família compara carteira administrada discricionária e fundo exclusivo buscando restrições personalizadas, transparência e governança.",prompt:"A comparação adequada reconhece que:",answer:"ambos podem individualizar a gestão, mas diferem em estrutura jurídica, titularidade, governança, custos e tratamento operacional.",distractors:["as duas estruturas são juridicamente idênticas.","fundo exclusivo dispensa prestadores e controles.","gestão discricionária exige autorização para cada ordem."]},
  {module:I2,reference:"PD C-Pro I 2.2",context:"Um fundo de private equity reporta TIR elevada, mas realizou poucas saídas, usa avaliações internas e chama capital ao longo do tempo.",prompt:"Ao comparar com ativos líquidos, é essencial:",answer:"examinar fluxos realizados, valuation, vintage, liquidez e o efeito do timing das chamadas sobre a TIR.",distractors:["comparar apenas a TIR com o CDI do último mês.","tratar valuation interno como caixa resgatável.","ignorar vintage porque ativos ilíquidos não passam por ciclos."]},
  {module:I2,reference:"PD C-Pro I 2.10",context:"Um protocolo DeFi remunera liquidity mining. O token cai, o pool sofre perda impermanente e o contrato inteligente não foi auditado.",prompt:"A decomposição adequada do risco inclui:",answer:"smart contract, preço dos tokens, perda impermanente, liquidez, governança e contraparte econômica do protocolo.",distractors:["apenas a volatilidade do token de recompensa.","somente risco soberano, pois blockchain substitui contraparte.","ausência de risco operacional porque o código é público."]},
  {module:I2,reference:"PD C-Pro I 2.9",context:"Uma carteira em reais compra Treasury Notes sem hedge. Os juros americanos sobem e o dólar se valoriza frente ao real.",prompt:"O retorno em reais deve considerar que:",answer:"queda do título e variação cambial são exposições distintas e podem compensar ou ampliar o resultado.",distractors:["a alta do dólar garante resultado positivo.","Treasuries não sofrem marcação antes do vencimento.","o câmbio afeta cupons, mas nunca o principal convertido."]},
  {module:I3,reference:"PD C-Pro I 3.4",context:"Uma contribuinte no modelo completo aporta em PGBL acima do limite fiscal aplicável e pretende deduzir todo o valor.",prompt:"O especialista deve explicar que:",answer:"o benefício depende dos requisitos e do limite sobre renda tributável; o excedente não amplia a dedução.",distractors:["todo aporte é integralmente dedutível.","PGBL nunca permite diferimento.","a dedução torna o resgate futuro isento."]},
  {module:I3,reference:"PD C-Pro I 3.3",context:"Uma cliente no modelo simplificado compara PGBL e VGBL com mesma carteira e custos, visando acumulação e sucessão.",prompt:"Quanto à base de IR na saída, deve-se destacar que:",answer:"no VGBL, em regra, incide sobre rendimentos; no PGBL, sobre o total, observadas as regras vigentes.",distractors:["em ambos incide sempre apenas sobre rendimentos.","no VGBL incide sobre o total e no PGBL apenas sobre rendimentos.","o modelo simplificado torna os dois isentos."]},
  {module:I3,reference:"PD C-Pro I 3.8",context:"Uma pessoa prevê resgates em três anos, possui renda tributável variável e compara regimes progressivo e regressivo.",prompt:"A decisão tecnicamente defensável é:",answer:"projetar prazo de cada contribuição, alíquota efetiva e ajuste na declaração, sem presumir superioridade universal do regressivo.",distractors:["escolher regressivo porque a menor alíquota vale desde o primeiro dia.","escolher progressivo porque nunca há retenção.","ignorar o cronograma e decidir apenas pela idade."]},
  {module:I3,reference:"PD C-Pro I 3.7",context:"Um participante quer renda vitalícia para si e proteção ao cônjuge após a morte, comparando renda simples e reversível.",prompt:"O trade-off esperado é:",answer:"a reversão protege o beneficiário e tende a reduzir a renda inicial, mantidas as demais premissas atuariais.",distractors:["a reversão eleva necessariamente a renda inicial.","a renda simples continua integralmente ao cônjuge.","as modalidades independem da tábua atuarial."]},
  {module:I3,reference:"PD C-Pro I 3.6",context:"Dois planos têm mesma carteira, mas tábuas biométricas, taxas de juros e condições de excedente diferentes na conversão em renda.",prompt:"A comparação deve considerar que:",answer:"tábua, taxa, reversão e excedente afetam o fator atuarial e o benefício convertido.",distractors:["somente o saldo determina a renda.","a tábua mais recente é sempre melhor.","excedente financeiro é sempre garantido e igual ao retorno do fundo."]},
  {module:I4,reference:"PD C-Pro I 4.2",context:"Uma carteira tem 60% no ativo A, retorno esperado de 10%, e 40% no B, retorno de 5%, com correlação baixa.",prompt:"O retorno esperado e o papel da correlação são:",answer:"8%; a correlação não altera a média ponderada, mas influencia a variância da carteira.",distractors:["7,5%; correlação reduz a média.","8%; correlação baixa elimina a volatilidade.","15%; os retornos são somados antes dos pesos."]},
  {module:I4,reference:"PD C-Pro I 4.5",context:"Fundo A rende 12% com volatilidade de 10%; B rende 11% com volatilidade de 6%. A taxa livre de risco é 5%.",prompt:"Pelo índice de Sharpe:",answer:"B tem Sharpe 1,0, superior ao 0,7 de A.",distractors:["A é superior porque retorno bruto sempre prevalece.","os índices são iguais porque ambos superam a taxa livre.","B é inferior porque volatilidade menor reduz o numerador."]},
  {module:I4,reference:"PD C-Pro I 4.5",context:"Um modelo informa VaR diário de R$ 2 milhões a 99%, e o comitê o interpreta como perda máxima absoluta.",prompt:"A correção metodológica é:",answer:"VaR é probabilístico sob hipóteses e horizonte definidos; perdas maiores são possíveis e pedem stress tests.",distractors:["VaR é a pior perda possível em qualquer cenário.","stress test é redundante com confiança de 99%.","o horizonte não altera a interpretação."]},
  {module:I4,reference:"PD C-Pro I 4.3",context:"Uma ação tem beta 1,3; taxa livre de risco de 6% e prêmio de mercado de 5%.",prompt:"Pelo CAPM, o retorno requerido é:",answer:"12,5%, por 6% + 1,3 × 5%.",distractors:["11%, pela soma simples da taxa e do prêmio.","7,5%, multiplicando a taxa livre pelo beta.","17,3%, somando beta como percentual."]},
];

const rb: Blueprint[] = [
  {module:R1,reference:"PD C-Pro R 1.1",context:"Após vender com perda, um cliente recusa reavaliar o ativo porque voltar seria admitir erro.",prompt:"A intervenção que melhor mitiga o viés é:",answer:"separar a decisão passada da análise atual e comparar cenários com critérios previamente definidos.",distractors:["usar o preço antigo como âncora.","garantir que a recompra recuperará a perda.","indicar o ativo de maior alta recente."],format:"dialogue",dialogue:[{speaker:"Cliente",text:"Recomprar seria admitir que errei."},{speaker:"Profissional",text:"A decisão de hoje precisa ser avaliada pelos dados de hoje."}]},
  {module:R1,reference:"PD C-Pro R 1.4",context:"Uma equipe gerou 400 leads, 80 reuniões, 20 propostas aceitas e 12 ativações.",prompt:"Para localizar o maior gargalo, deve-se:",answer:"calcular conversões por etapa e investigar qualidade e processo, não apenas volume inicial.",distractors:["medir somente ativações.","aumentar leads antes de analisar conversão.","tratar proposta e ativação como a mesma etapa."]},
  {module:R1,reference:"PD C-Pro R 1.6",context:"Um cliente pede operação incompatível e diz que assinará um termo para eliminar a análise de adequação.",prompt:"A resposta profissional é:",answer:"seguir procedimentos, alertar e documentar; o termo não torna o produto adequado nem elimina deveres.",distractors:["executar sem alertas.","alterar o perfil apenas para liberar a ordem.","ocultar riscos para preservar autonomia."],format:"dialogue",dialogue:[{speaker:"Cliente",text:"Eu assino qualquer termo; faça a aplicação."},{speaker:"Profissional",text:"A formalização não substitui a análise."}]},
  {module:R2,reference:"PD C-Pro R 2.1",context:"Um casal tem renda líquida de R$ 24 mil, gastos de R$ 15 mil, dívidas de R$ 3 mil e despesas eventuais variáveis.",prompt:"Ao estimar poupança recorrente, o profissional deve:",answer:"separar fluxos recorrentes dos eventuais e validar sustentabilidade antes de fixar aportes.",distractors:["tratar toda sobra contábil como aporte fixo.","usar renda bruta e ignorar despesas.","classificar serviço da dívida como investimento."]},
  {module:R2,reference:"PD C-Pro R 2.2",context:"Uma família tem R$ 100 mil em ativo D+60 e obrigação de R$ 70 mil em dez dias; o ativo tem baixa volatilidade.",prompt:"O diagnóstico correto é:",answer:"há descasamento de liquidez apesar da baixa volatilidade, exigindo planejamento de caixa.",distractors:["não há risco porque o ativo supera a dívida.","D+60 atende uma obrigação em dez dias.","baixa volatilidade torna o ativo caixa imediato."]},
  {module:R2,reference:"PD C-Pro R 2.4",context:"Uma cliente se diz arrojada, mas precisa de todo o capital para cirurgia em quatro meses e não tem outra fonte.",prompt:"Na adequação dessa parcela, prevalece:",answer:"a baixa capacidade objetiva de perda e o horizonte curto, apesar da tolerância declarada.",distractors:["a autodeclaração arrojada.","o retorno dos últimos quatro meses.","o perfil médio da família."]},
  {module:R3,reference:"PD C-Pro R 3.1",context:"Um cliente tem metas em 1, 7 e 25 anos; a proposta usa a mesma carteira ilíquida para todas.",prompt:"A correção da indicação deve:",answer:"segmentar objetivos por horizonte e caixa, articulando reserva, médio prazo e crescimento.",distractors:["usar uma carteira única porque diversificação resolve prazos.","financiar metas curtas com crédito.","priorizar o produto de maior taxa."]},
  {module:R3,reference:"PD C-Pro R 3.1.4",context:"A carteira reúne ações, FII, debêntures do mesmo setor e imóvel familiar, sendo descrita como amplamente diversificada.",prompt:"Qual análise corrige o diagnóstico?",answer:"mapear fatores comuns de setor, economia doméstica, crédito e imóveis; quantidade de rótulos não basta.",distractors:["contar quatro produtos prova diversificação.","excluir o imóvel do risco patrimonial.","assumir correlação zero entre classes."]},
  {module:R3,reference:"PD C-Pro R 3.2.1",context:"Uma cliente precisa de caixa em 18 meses e considera prefixado de dez anos para vender antes se necessário.",prompt:"O alerta essencial é:",answer:"venda antecipada envolve marcação e liquidez; prazo do ativo deve ser compatível com a meta.",distractors:["a taxa contratada vale em qualquer data de venda.","prazo longo reduz sensibilidade a juros.","custódia elimina oscilação de preço."]},
  {module:R3,reference:"PD C-Pro R 3.2.1",context:"Um cliente distribui CDBs por marcas do mesmo conglomerado e acredita multiplicar a cobertura do FGC.",prompt:"A orientação adequada é:",answer:"verificar consolidação por conglomerado e CPF, limites aplicáveis e risco excedente à garantia.",distractors:["cada marca gera cobertura integral independente.","vencimentos diferentes eliminam o teto.","agências diferentes eliminam concentração."]},
  {module:R3,reference:"PD C-Pro R 3.2.2",context:"Um cliente compra multimercado alavancado pelo retorno, mas não compreende o drawdown de 14%.",prompt:"A explicação central é:",answer:"mandato flexível e alavancagem podem ampliar perdas; retorno passado não substitui capacidade de perda.",distractors:["alavancagem garante superar CDI.","drawdown mede crédito do administrador.","multimercado não sofre risco de derivativos."],format:"dialogue",dialogue:[{speaker:"Cliente",text:"Se bateu o CDI, por que olhar a queda máxima?"},{speaker:"Profissional",text:"O caminho e a perda suportável importam."}]},
  {module:R3,reference:"PD C-Pro R 3.7",context:"Uma cliente no modelo completo compara PGBL e VGBL apenas pelo retorno da carteira.",prompt:"A indicação deve incorporar:",answer:"dedução possível, base de IR na saída, custos, prazo, renda e objetivo sucessório.",distractors:["apenas retorno, pois os produtos são iguais.","PGBL sempre, porque tudo é dedutível.","VGBL sempre, porque o resgate é isento."],format:"dialogue",dialogue:[{speaker:"Cliente",text:"Se os fundos rendem igual, tanto faz?"},{speaker:"Profissional",text:"A tributação e a finalidade dependem da sua situação."}]},
  {module:R4,reference:"PD C-Pro R 4.2",context:"Uma carteira financia mensalidades por cinco anos e aposentadoria em vinte; o relatório mede apenas retorno consolidado.",prompt:"Para monitorar adequadamente, deve-se:",answer:"acompanhar cada meta, liquidez, inflação, risco e probabilidade de alcance, além do retorno agregado.",distractors:["usar apenas retorno total.","comparar tudo ao CDI.","ignorar retiradas até o primeiro saque."]},
  {module:R4,reference:"PD C-Pro R 4.4",context:"Após queda, a carteira saiu das bandas e a cliente quer congelar pesos por aversão a novas perdas.",prompt:"A abordagem coerente é:",answer:"revisitar perfil e objetivos e aplicar a regra de rebalanceamento se as premissas permanecerem válidas.",distractors:["comprar apenas para recuperar perdas.","abandonar a política em toda queda.","rebalancear sem checar liquidez ou mudança de perfil."],format:"dialogue",dialogue:[{speaker:"Cliente",text:"Não quero comprar algo que caiu."},{speaker:"Profissional",text:"Vamos decidir pelo risco-alvo, não pela perda recente."}]},
  {module:R4,reference:"PD C-Pro R 4.9",context:"Fundos X e Y renderam 11%. X teve volatilidade de 8% e distribuição simétrica; Y, 6%, mas cauda negativa relevante.",prompt:"Ao comparar Sharpe e Sharpe modificado:",answer:"a medida modificada pode penalizar melhor a assimetria e a cauda que a volatilidade isolada subestima.",distractors:["menor volatilidade torna Y sempre superior.","Sharpe modificado ignora distribuição.","cauda negativa aumenta o índice."]},
];

const variants = [
  "No comitê mensal, os dados abaixo precisam sustentar uma decisão.",
  "Durante a revisão trimestral, o cliente questiona a recomendação anterior.",
  "Em um cenário de maior volatilidade, a equipe refaz a análise sem alterar os fatos centrais.",
];

function expand(exam: ExamCode, blueprints: Blueprint[], repeats: number): Question[] {
  let n = 0;
  return blueprints.flatMap((b, bi) => Array.from({length: repeats}, (_, vi) => {
    n += 1;
    const options = [b.answer, ...b.distractors];
    const shift = (n * 3) % 4;
    const rotated = [...options.slice(shift), ...options.slice(0, shift)];
    return {
      id:`${exam.toLowerCase()}-${String(n).padStart(2,"0")}`, exam, module:b.module,
      format:b.format ?? "case", difficulty: vi === 1 && bi % 3 === 0 ? "Médio" : "Difícil",
      cognitiveLevel: bi % 4 === 0 ? "Aplicação" : "Análise",
      context:`${variants[vi]} ${b.context}`,
      dialogue:b.dialogue?.map((line, i) => i === 1 && vi > 0 ? {...line,text:`${line.text} ${vi === 1 ? "Comparemos também o cenário alternativo." : "Quantifiquemos o impacto antes de agir."}`} : line),
      prompt: vi === 0 ? b.prompt : `${b.prompt} Considere especialmente ${vi === 1 ? "a interação entre risco e objetivo" : "as consequências da decisão no cenário adverso"}.`,
      options:rotated, correctIndex:rotated.indexOf(b.answer),
      explanation:`${b.answer} A resolução exige aplicar os dados do caso, evitando conclusões baseadas em um único indicador.`, reference:b.reference,
    } satisfies Question;
  }));
}

export const questionBank: Question[] = [...expand("CPRO_I", ib, 2), ...expand("CPRO_R", rb, 3)];
export const officialModules = { CPRO_I:[I1,I2,I3,I4], CPRO_R:[R1,R2,R3,R4] };
