import type { ExamCode, Question } from "./types";

type Blueprint = Omit<Question, "id" | "exam" | "correctIndex" | "options"> & { answer: string; distractors: string[] };

const people = ["Ana", "Bruno", "Carla", "Diego", "Elisa", "Felipe", "Giovana", "Henrique", "Isabela", "João"];

const iBlueprints: Blueprint[] = [
  { module: "1. Produtos de investimentos", format: "case", difficulty: "Difícil", context: "Uma carteira possui título prefixado longo e o mercado passa a projetar alta relevante da curva de juros.", prompt: "Qual efeito técnico deve ser destacado no relatório?", answer: "O preço do título tende a cair, com impacto maior quanto maior for sua duration modificada.", distractors: ["O preço tende a subir porque o cupom permanece fixo.", "A marcação a mercado não afeta títulos mantidos em carteira.", "A duration elimina o risco de oscilação da taxa."], explanation: "Preço e taxa de juros se movem em sentidos opostos. A duration modificada aproxima a sensibilidade percentual do preço à variação da taxa.", reference: "PD C-Pro I 1.7.2.5.2 e 1.7.2.5.3" },
  { module: "1. Produtos de investimentos", format: "multiple", difficulty: "Médio", context: "Uma pessoa investidora compara um FII listado com um fundo de renda fixa aberto.", prompt: "Qual diferença é tecnicamente correta?", answer: "No FII, a saída normalmente ocorre pela venda da cota no mercado secundário, sujeita à liquidez de negociação.", distractors: ["Todo FII garante recompra diária pelo administrador.", "O FII possui cobertura ordinária do FGC.", "Fundos abertos só permitem resgate no mercado secundário."], explanation: "FIIs são, em regra, fundos fechados; a liquidez do cotista ocorre pela negociação das cotas no mercado secundário.", reference: "PD C-Pro I 1.2.1" },
  { module: "1. Produtos de investimentos", format: "multiple", difficulty: "Médio", context: "Um fundo cobra taxa de performance e ficou abaixo do seu maior valor de cota ajustado no período anterior.", prompt: "Qual princípio deve ser observado antes de nova cobrança?", answer: "A linha d’água, evitando taxa de performance sobre simples recuperação de perda anterior.", distractors: ["A cobertura do FGC.", "A isenção automática de come-cotas.", "A conversão obrigatória em fundo fechado."], explanation: "A linha d’água impede nova cobrança até que o desempenho recupere o nível de referência aplicável.", reference: "PD C-Pro I 1.1.8.1" },
  { module: "1. Produtos de investimentos", format: "case", difficulty: "Médio", context: "Uma investidora quer exposição a debênture incentivada, mas exige proteção do FGC.", prompt: "Como o especialista deve orientar?", answer: "Explicar que debêntures não contam com FGC e que há risco de crédito do emissor, apesar do possível benefício tributário.", distractors: ["Confirmar cobertura integral do FGC até o vencimento.", "Informar que o Tesouro Nacional garante a emissão.", "Dizer que a isenção fiscal elimina o risco de crédito."], explanation: "Debêntures são títulos de dívida corporativa e não estão entre os instrumentos cobertos pelo FGC.", reference: "PD C-Pro I 1.7.2.2.6 e 1.7.2.6" },
  { module: "2. Alternativos, digitais e exterior", format: "case", difficulty: "Difícil", context: "Um comitê avalia stablecoins e protocolos DeFi para uma parcela alternativa de carteira.", prompt: "Qual análise é indispensável?", answer: "Avaliar mecanismo de lastro, liquidez, custódia, contratos inteligentes e riscos de contraparte e regulatório.", distractors: ["Considerar todas as stablecoins equivalentes a depósitos bancários.", "Ignorar risco operacional quando houver blockchain pública.", "Usar apenas a valorização histórica como medida de segurança."], explanation: "Ativos digitais combinam riscos tecnológicos, de custódia, liquidez, contraparte e regulação; retorno passado isolado não é suficiente.", reference: "PD C-Pro I 2.10" },
  { module: "2. Alternativos, digitais e exterior", format: "multiple", difficulty: "Médio", context: "Uma carteira concentrada no Brasil busca diversificação internacional.", prompt: "Qual benefício e risco devem ser avaliados conjuntamente?", answer: "Redução da concentração doméstica e exposição ao risco cambial, regulatório e de mercado externo.", distractors: ["Eliminação de todo risco de mercado e ausência de variação cambial.", "Cobertura obrigatória do FGC para qualquer ativo externo.", "Isenção tributária automática para todo investimento internacional."], explanation: "A diversificação geográfica pode reduzir riscos específicos locais, mas adiciona riscos cambiais, legais e dos mercados de destino.", reference: "PD C-Pro I 2.9" },
  { module: "3. Previdência complementar", format: "case", difficulty: "Médio", context: "Uma cliente declara IR no modelo completo, tem renda tributável e pretende acumular recursos por longo prazo.", prompt: "Qual análise inicial é mais adequada entre PGBL e VGBL?", answer: "Verificar se as contribuições ao PGBL podem gerar benefício fiscal dentro do limite legal e lembrar que o IR incide sobre o total resgatado.", distractors: ["Recomendar VGBL porque sempre permite deduzir contribuições.", "Afirmar que PGBL é isento de IR no resgate.", "Escolher apenas pela rentabilidade passada do fundo."], explanation: "No PGBL, respeitadas as condições legais, contribuições podem ser deduzidas; em contrapartida, o IR incide sobre o total no resgate/benefício.", reference: "PD C-Pro I 3.4 a 3.8" },
  { module: "3. Previdência complementar", format: "multiple", difficulty: "Médio", context: "Um participante quer mover sua reserva entre planos de previdência sem receber os recursos.", prompt: "O que caracteriza a portabilidade?", answer: "Transferência direta da reserva entre planos compatíveis, sem disponibilização do valor ao participante.", distractors: ["Resgate seguido de novo aporte em conta corrente.", "Empréstimo garantido pela reserva com incidência imediata de IR.", "Conversão obrigatória de PGBL em VGBL."], explanation: "Portabilidade é transferência direta entre planos, observadas as regras de compatibilidade, e não se confunde com resgate.", reference: "PD C-Pro I 3.10" },
  { module: "4. Risco, carteiras e performance", format: "case", difficulty: "Difícil", context: "Dois fundos têm o mesmo retorno. O Fundo A apresenta volatilidade menor e taxa livre de risco positiva.", prompt: "Pelo índice de Sharpe, qual tende a ser preferível?", answer: "O Fundo A, pois entrega maior retorno excedente por unidade de risco, mantidas as demais condições.", distractors: ["O Fundo de maior volatilidade, porque Sharpe premia risco isoladamente.", "São necessariamente iguais, pois Sharpe considera apenas retorno bruto.", "Não é possível usar taxa livre de risco no cálculo."], explanation: "Sharpe relaciona retorno excedente à volatilidade. Com retornos iguais, a menor volatilidade eleva o índice.", reference: "PD C-Pro I 4.4" },
  { module: "4. Risco, carteiras e performance", format: "multiple", difficulty: "Médio", context: "Após forte alta da renda variável, sua participação supera o limite definido na política da carteira.", prompt: "Qual ação representa rebalanceamento disciplinado?", answer: "Reduzir a parcela excedente e recompor os pesos-alvo, considerando custos, tributos e perfil.", distractors: ["Manter o desvio indefinidamente porque o ativo valorizou.", "Vender toda a carteira e manter apenas caixa.", "Aumentar ainda mais a posição sem rever o risco."], explanation: "Rebalancear restaura o risco planejado, sem dispensar a análise de custos, tributação e adequação.", reference: "PD C-Pro I 4.6" },
];

const rBlueprints: Blueprint[] = [
  { module: "1. Prospecção e relacionamento", format: "dialogue", difficulty: "Médio", context: "Primeira conversa com uma potencial cliente indicada por outra pessoa.", dialogue: [{ speaker: "Cliente", text: "Quero dobrar meu dinheiro rápido, mas não aceito perder nada." }, { speaker: "Profissional", text: "Antes de falar de produtos, quero entender seus objetivos, prazo e experiência." }], prompt: "Qual deve ser o próximo passo da profissional?", answer: "Explorar necessidades e tolerância a perdas, alinhar expectativas e só depois apresentar alternativas adequadas.", distractors: ["Prometer o produto com maior retorno passado.", "Omitir riscos para evitar resistência comercial.", "Classificar a cliente como arrojada apenas pelo objetivo de retorno."], explanation: "A abordagem consultiva começa pela compreensão do cliente e pelo alinhamento entre retorno esperado, prazo, capacidade e tolerância ao risco.", reference: "PD C-Pro R 1" },
  { module: "1. Prospecção e relacionamento", format: "dialogue", difficulty: "Médio", context: "Atendimento após queda de mercado.", dialogue: [{ speaker: "Cliente", text: "Vi a carteira cair e quero vender tudo agora." }, { speaker: "Profissional", text: "Entendo a preocupação. Vamos revisar o objetivo e o prazo antes de decidir." }], prompt: "Qual conduta reduz a influência do viés emocional?", answer: "Relembrar o plano, quantificar impactos das alternativas e avaliar se houve mudança real no objetivo ou perfil.", distractors: ["Executar a venda sem contextualizar para encerrar a tensão.", "Garantir recuperação em prazo determinado.", "Ignorar o cliente até o mercado se recuperar."], explanation: "Escuta ativa, reenquadramento do objetivo e comparação de cenários ajudam a evitar decisões impulsivas sem retirar a autonomia do cliente.", reference: "PD C-Pro R 1.6 e 4.1" },
  { module: "2. Análise de informações do cliente", format: "case", difficulty: "Difícil", context: "Um cliente se declara arrojado, mas sua reserva será usada integralmente para entrada de imóvel em seis meses.", prompt: "Qual informação deve prevalecer na recomendação para essa reserva?", answer: "O prazo curto, a finalidade essencial e a baixa capacidade de suportar perda, mesmo com tolerância declarada elevada.", distractors: ["Somente a autodeclaração de perfil arrojado.", "A rentabilidade do produto no último mês.", "A comissão disponível ao distribuidor."], explanation: "Suitability considera objetivos, horizonte, situação financeira, conhecimento e tolerância. Uma necessidade de curto prazo limita o risco suportável.", reference: "PD C-Pro R 2" },
  { module: "2. Análise de informações do cliente", format: "multiple", difficulty: "Médio", context: "O cadastro e a análise de perfil de uma cliente estão desatualizados após mudança relevante de renda e objetivos.", prompt: "Qual é a conduta adequada?", answer: "Atualizar as informações e reavaliar a adequação antes de nova indicação.", distractors: ["Usar indefinidamente o perfil antigo.", "Dispensar a análise porque a cliente já investiu antes.", "Alterar o perfil sem consultar a cliente."], explanation: "Mudanças relevantes exigem atualização das informações para que a indicação continue adequada.", reference: "PD C-Pro R 2" },
  { module: "3. Indicação de investimentos", format: "case", difficulty: "Médio", context: "Uma cliente conservadora precisa de reserva de emergência e valoriza disponibilidade imediata.", prompt: "Qual característica deve receber prioridade?", answer: "Liquidez, baixa oscilação e compatibilidade com o prazo de uso, sem buscar retorno elevado a qualquer custo.", distractors: ["Prazo de carência longo e alta volatilidade.", "Concentração em criptoativos.", "Produto sem possibilidade de resgate antes do vencimento."], explanation: "Reserva de emergência deve priorizar acesso e preservação, respeitando o perfil e a finalidade do recurso.", reference: "PD C-Pro R 3" },
  { module: "3. Indicação de investimentos", format: "dialogue", difficulty: "Difícil", context: "Conversa sobre previdência.", dialogue: [{ speaker: "Cliente", text: "Faço declaração simplificada e quero investir para sucessão e aposentadoria." }, { speaker: "Profissional", text: "Vamos comparar PGBL e VGBL, regimes tributários, custos e beneficiários." }], prompt: "Qual ponto é essencial na comparação?", answer: "No VGBL, o IR incide em regra sobre os rendimentos; no PGBL, sobre o total resgatado, além das condições de dedução das contribuições.", distractors: ["Ambos são sempre isentos de IR.", "PGBL e VGBL possuem exatamente a mesma base tributável.", "O regime regressivo sempre é melhor, independentemente do prazo."], explanation: "A base de incidência e o possível benefício fiscal diferem. A escolha exige analisar declaração, renda, prazo e objetivo.", reference: "PD C-Pro R 3.7" },
  { module: "3. Indicação de investimentos", format: "case", difficulty: "Médio", context: "Uma pessoa quer aplicar toda a reserva em um único ativo de alto risco após vê-lo subir nas redes sociais.", prompt: "Qual resposta é mais apropriada?", answer: "Explicar riscos, concentração e aderência ao perfil, comparando uma alocação diversificada sem prometer retorno.", distractors: ["Confirmar que a alta recente continuará.", "Executar sem alertas porque a decisão é do cliente.", "Dizer que diversificação elimina qualquer possibilidade de perda."], explanation: "A orientação deve ser clara, adequada e sem promessa, destacando concentração e riscos específicos.", reference: "PD C-Pro R 3.8 e 4.7" },
  { module: "4. Análise e monitoramento", format: "case", difficulty: "Difícil", context: "A carteira tem ativos com correlação baixa e pesos equilibrados.", prompt: "Qual é o principal efeito esperado da diversificação?", answer: "Reduzir o risco não sistemático da carteira, sem garantir ausência de perdas.", distractors: ["Eliminar todo risco de mercado.", "Aumentar necessariamente o retorno de todos os ativos.", "Tornar a volatilidade igual à soma simples das volatilidades."], explanation: "A covariância entre ativos influencia o risco conjunto; diversificação reduz risco específico, mas não remove risco sistêmico.", reference: "PD C-Pro R 4.7 e 4.8" },
  { module: "4. Análise e monitoramento", format: "multiple", difficulty: "Médio", context: "Um evento de vida altera o horizonte e a necessidade de renda de uma cliente.", prompt: "Como proceder no monitoramento?", answer: "Revisar objetivos, perfil e carteira, documentando a nova análise e os impactos tributários e de liquidez.", distractors: ["Manter a carteira sem revisão até o vencimento de todos os ativos.", "Trocar os produtos apenas pelo ranking de rentabilidade.", "Desconsiderar custos e tributação no rebalanceamento."], explanation: "Monitoramento é contínuo e deve incorporar eventos de vida, adequação, custos, tributos e liquidez.", reference: "PD C-Pro R 4.2 e 4.4" },
  { module: "4. Análise e monitoramento", format: "multiple", difficulty: "Médio", context: "Duas carteiras apresentam o mesmo risco estimado, mas retornos esperados diferentes.", prompt: "Pelo princípio da dominância, qual tende a ser preferida?", answer: "A de maior retorno esperado para o mesmo nível de risco, mantidas as demais premissas.", distractors: ["A de menor retorno, porque risco igual impede comparação.", "As duas são sempre equivalentes.", "A mais concentrada, independentemente do retorno."], explanation: "Para risco igual, domina a alternativa com maior retorno esperado; para retorno igual, domina a de menor risco.", reference: "PD C-Pro R 4.6 e 4.9" },
];

function rotate<T>(items: T[], shift: number): T[] {
  const offset = shift % items.length;
  return [...items.slice(offset), ...items.slice(0, offset)];
}

function expand(exam: ExamCode, blueprints: Blueprint[], count: number): Question[] {
  return Array.from({ length: count }, (_, index) => {
    const source = blueprints[index % blueprints.length];
    const person = people[index % people.length];
    const repetition = Math.floor(index / blueprints.length) + 1;
    const options = rotate([source.answer, ...source.distractors], index);
    return {
      ...source,
      id: `${exam.toLowerCase()}-${String(index + 1).padStart(2, "0")}`,
      exam,
      context: `${person} participa do cenário ${repetition}. ${source.context}`,
      options,
      correctIndex: options.indexOf(source.answer),
    };
  });
}

export const questionBank: Question[] = [
  ...expand("CPRO_I", iBlueprints, 40),
  ...expand("CPRO_R", rBlueprints, 45),
];

export const officialModules = {
  CPRO_I: ["1. Produtos de investimentos", "2. Alternativos, digitais e exterior", "3. Previdência complementar", "4. Risco, carteiras e performance"],
  CPRO_R: ["1. Prospecção e relacionamento", "2. Análise de informações do cliente", "3. Indicação de investimentos", "4. Análise e monitoramento"],
};
